### PR TITLE
docs(layout): improve UI/UX of the presentation

### PR DESCRIPTION
**Pull request by zoltanszogyenyi**
Hey @shinokada,

First of all great job for the contribution!

This PR serves the purpose to improve the presentation and UI/UX for the Flowbite Svelte Blocks repository.

## 📑 Description

I have improved the homepage, the main navbar, content, and you can also check out this page for the main content area too:

`http://localhost:5173/application/advanced-tables`

The changes I've made here have to be added to 132 files which is not sustainable so we need to create a separate component where the layout itself will be modified in one place and we only pass the actual data as props (ie. title, description, GitHub link, code example).

I've described the issue here: https://github.com/shinokada/flowbite-svelte-blocks/issues/15

I have also updated the navbar in two places already (the main layout and the one for application) but I have to do that for marketing and e-commerce too? Let's just have on navbar if possible just like the footer.

- [x] Completed

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [x] My code requires changes to the documentation
- [x] I have updated the documentation as required
- [x] All the tests have passed

## ℹ Additional Information

We should also update the titles to something like this:

`Svelte Advanced Tables - Flowbite`
`Svelte Header - Flowbite`
`Svelte CRUD Modals - Flowbite`

To put an emphasis on Svelte rather than Tailwind CSS.

### CODE REVIEW

**Comment by zoltanszogyenyi** [comment]
Before:

Screenshot 2023-03-25 at 15 02 19

After:

Screenshot 2023-03-25 at 15 02 14

This should be applied to all the pages - spacings and margins have been improved.

**Comment by shinokada** [comment]
Please let me know when it is ready to be merged.

**Comment by shinokada** [comment]
I updated and you can see the [details](https://github.com/shinokada/flowbite-svelte-blocks/pull/17).

You need to modify [one file](https://github.com/shinokada/flowbite-svelte-blocks/blob/main/src/routes/utils/SectionBlock.svelte) to style the section block.

I will update layouts soon.

**Comment by shinokada** [comment]
I updated [layouts](https://github.com/shinokada/flowbite-svelte-blocks/pull/18).

Please proceed updating your PR.

**Comment by zoltanszogyenyi** [comment]
Hey @shinokada,

Thanks for the layout updates - I've finished my part by updating UI/UX related spacings, margins, containers.

I have also updated the expected titles to match a better SEO expectation.

Do you think we could upload this to Flowbite-Svelte.com eventually? I'm thinking we could use a worker or GitHub pages.

Something like:

https://flowbite-svelte.com/blocks/...

Tests have passed, but please double-check if everything works okay.

Cheers,
Zoltan

**Comment by shinokada** [comment]
@zoltanszogyenyi Thanks. Yes, it is a good idea to move to flowbite-svelte.com/blocks.

**Pull request merged**
